# Generated by Django 5.2.1 on 2025-06-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_original_cart_order_stripe_pid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_area',
            field=models.CharField(choices=[('london', 'London'), ('manchester', 'Manchester'), ('birmingham', 'Birmingham'), ('glasgow', 'Glasgow')], default='london', max_length=50),
        ),
    ]
