# Generated by Django 5.2.1 on 2025-06-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_remove_order_country_order_delivery_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_area',
            field=models.CharField(choices=[('london', 'London')], default='london', max_length=50),
        ),
    ]
