# Generated by Django 5.2.1 on 2025-06-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_slug_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-is_featured', 'category__order', 'name'], 'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer Review', 'verbose_name_plural': 'Customer Reviews'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='track_stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Dish image', null=True, upload_to='products/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.TextField(help_text='List of ingredients used in this dish'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Is this item currently available?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Display as featured item'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='Additional dish image', upload_to='products/gallery/'),
        ),
        migrations.DeleteModel(
            name='NutritionalInfo',
        ),
    ]
