# Generated by Django 5.2.1 on 2025-06-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Dish image', null=True, upload_to='products/images/'),
        ),
    ]
